version: '2.1'

services:
  postgres:
    image: ghcr.io/lunatech-labs/lunatech-imdb-assessment-db:1.0-xs
    container_name: lunatech-imdb-assessment-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lunatech_imdb
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

